### PR TITLE
Create Options Page

### LINKED ISSUE #1: Allow setting the Fiddler host and port number
The Fiddler host and port number is currently hardcoded to localhost:8888. It would be nice if it could be configured by the user.

Tasks:

- [ ] Create settings page
- [ ] Change PAC to listen to the settings
- [ ] When settings are changed and PAC active, update PAC info

### PR DESCRIPTION
**Pull request by mitsakosgr**
- Fixed Icons (corrupted)
- Added options page for Proxy host/port
- Added options to filter urls to send to proxy

Partially closes https://github.com/Sebazzz/fiddlerfox/issues/1, except auto reloading PAC when settings are changed. User needs to manually disable and re-enable the proxy (clicking twice on extension).

### CODE REVIEW

**Comment by Sebazzz** [comment]
Excellent, will look at it after work 😄

**Comment by Sebazzz** [comment]
Unfortunately it does not work, or not for me at least (Firefox 88b8).

Icon is broken: 
image

This possibly also causes the toolbar icon not to appear.

Possible issues (but I haven't checked whether these weren't present already) causing the toolbar icon not to appear:
image

The PNG files appear to be corrupted.

**Comment by mitsakosgr** [comment]
It doesn't work for me either. It must have been something with git and how it handles the files. I'll try to add an svg and see the results.

**Comment by Sebazzz** [comment]
Might be due to the `.gitattributes` file.

**Comment by mitsakosgr** [comment]
I replaced png with an svg. Give it a try again please.

**Comment by mitsakosgr** [comment]
> 
> 
> Might be due to the `.gitattributes` file.

According to these
https://stackoverflow.com/a/29508751
https://blog.jongallant.com/2021/02/png-files-not-rendering-on-github/

`* text eol=lf` alone will corrupt png files because they are not detected as binary.
You ahould also add `*.png binary` to treat them as binary files.
https://gist.github.com/dpalomar/ebc64d6f56cfc25a3e5c20fe7cdfbd4f

If the svg works, I think, it is better because of the smaller size and text format. I don't know about performance, but I don't think it is an issue for this case!

**Comment by Sebazzz** [comment]
Excellent work! I've added a stylesheet to the settings page, so it fits in nicely in the add-ons page. Published at v1.0.

Thank you!

**Pull request merged**
